
(pip._internal.exceptions.MetadataInvalid‹
/Users/test/Documents/ALFORIS FINANCE/06. CRM/V1/crm-backend/temp-venv/lib/python3.12/site-packages/pip/_internal/exceptions.pyî î("2*ú
2
ï ï(p
n

ï ï(4*
(pip._internal.exceptions.MetadataInvalid"
ireq"__id*$

__unknown_file (

ireqr
p

ð ð(5*
(pip._internal.exceptions.MetadataInvalid"
error"__id*%

__unknown_file (	

error*
3*f
3
exceptions.py<:
ò ò(
%1"(pip._internal.exceptions.MetadataInvalid"
ò ò(

%1:

î î(/
ireq:

î1 î(;
errorB,*
(pip._internal.exceptions.MetadataInvalidH