
2pip._internal.exceptions.NoneMetadataError.__str__‹
/Users/test/Documents/ALFORIS FINANCE/06. CRM/V1/crm-backend/temp-venv/lib/python3.12/site-packages/pip/_internal/exceptions.pyù ù("2*¯
2
ü ü(Xy
w

ü ü()
%1"__id*]

__unknown_file (A*?,
*pip._internal.exceptions.NoneMetadataError"
metadata_namep
n

üM ü(V
%2"__id*T

__unknown_file (8*6,
*pip._internal.exceptions.NoneMetadataError"
distš
—

ü ü(X
%3"__concat*

ü ü(	
None *

ü ü()

%1*4

ü* ü(L&$
" metadata found for distribution: *

üM ü(V

%2"

ü ü(X

%3B.,
*pip._internal.exceptions.NoneMetadataErrorH